export const POST_EMPLOYER = "POST_EMPLOYER";
export const POST_EMPLOYER_SUCCESS = "POST_EMPLOYER_SUCCESS";
export const POST_EMPLOYER_FAIL = "POST_EMPLOYER_FAIL";

export const UPDATE_EMPLOYER = "UPDATE_EMPLOYER";
export const UPDATE_EMPLOYER_SUCCESS = "UPDATE_EMPLOYER_SUCCESS";
export const UPDATE_EMPLOYER_FAIL = "UPDATE_EMPLOYER_FAIL";

export const LOGIN_EMPLOYER = "LOGIN_EMPLOYER";
export const LOGIN_EMPLOYER_SUCCESS = "LOGIN_EMPLOYER_SUCCESS";
export const LOGIN_EMPLOYER_FAIL = "LOGIN_EMPLOYER_FAIL";

export const GET_EMPLOYER = "GET_EMPLOYER";
export const GET_EMPLOYER_SUCCESS = "GET_EMPLOYER_SUCCESS";
export const GET_EMPLOYER_FAIL = "GET_EMPLOYER_FAIL";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const INVITE_STUDENTS = "INVITE_STUDENTS";
export const INVITE_STUDENTS_SUCCESS = "INVITE_STUDENTS_SUCCESS";
export const INVITE_STUDENTS_FAIL = "INVITE_STUDENTS_FAIL";

export const RESEND_PASSWORD = "RESEND_PASSWORD";
export const RESEND_PASSWORD_SUCCESS = "RESEND_PASSWORD_SUCCESS";
export const RESEND_PASSWORD_FAIL = "RESEND_PASSWORD_FAIL";

export const DESTROY_EMPLOYER_STATE = "DESTROY_EMPLOYER_STATE";
export const DESTROY_EMPLOYER_STATE_FAIL = "DESTROY_EMPLOYER_STATE_FAIl";
export const DESTROY_EMPLOYER_STATE_SUCCESS = "DESTROY_EMPLOYER_STATE_SUCCESS";

export const CHANGE_EMPLOYER_VALUE = "CHANGE_EMPLOYER_VALUE";
export const CLEAR_INFO = "CLEAR_INFO";