export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';

export const POST_STUDENT = 'POST_STUDENT';
export const POST_STUDENT_SUCCESS = 'POST_STUDENT_SUCCESS';
export const POST_STUDENT_FAIL = 'POST_STUDENT_FAIL';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';

export const SEARCH_STUDENT = "SEARCH_STUDENT";
export const SEARCH_STUDENT_SUCCESS = "SEARCH_STUDENT_SUCCESS";
export const SEARCH_STUDENT_FAIL = "SEARCH_STUDENT_FAIL";

export const DESTROY_STUDENT_STATE = "DESTROY_STUDENT_STATE";
export const DESTROY_STUDENT_STATE_FAIL = "DESTROY_STUDENT_STATE_FAIl";
export const DESTROY_STUDENT_STATE_SUCCESS = "DESTROY_STUDENT_STATE_SUCCESS";

export const CHANGE_VALUE = 'CHANGE_VALUE';
export const CHANGE_TAGS = 'CHANGE_TAGS';

export const CLEAR_STUDENT_INFO = 'CLEAR_STUDENT_INFO';

export const LOGIN = 'LOGIN';